#include <iostream>
#include <thread>

int main(){
    std::cout <<"____XXXXXX__________________________________XXX__XXХ" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"___XX_XXXXXXX____________________________XXXXX_XX_XX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"___XX___XXXXXXX________________________XXXXX_X____XX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"___XX_____XXXXXXX_____________________XXXXXXX_____XX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"__XXX__XX___XXXXXXX_________________XXXXXXX___XX__XX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"__XXX_____X___XXXXXXX_____XX______XXXXXXXX__X_____XX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"__XXXXX_____X__XXXXXXXXXXXXXXXXXXXXXXXXX__X___XXX_XX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"___XX___XX___XX_XXXXXXXXXXXXXXXXXXXXXXXXX__XX_____XX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"___XX_X____XX_XXXXXXXXXXXX___XXXXXXXXXXXXX___XXXX_XX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"___XX____XX_XXXXXXXXXXXX_`````_XXXXXXXXXXXXX_____XXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"___XXXXXX__XXX_```_XXXX_```````_XXX_``````_XXXX__XX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"____XX____XX```````_`X``````````_X``````````XXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"____XX___X_```_$$$$$__X`````````X`_$$$$$$````XXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_____XX_XX```$$$$$$$$$_X```````_`_$$$$$$$$````XXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"______XXX_``_$$$$$$$$$_X```````X_$$$$$$$$$_```XXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"______XXX_``_$$$$$$$$$__```````X_$$$$$$$$$_``_XXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"______XXXX```$$$$$$$$$__```````X`_$$$$$$$$```_XXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"______XXXXX___$$$$$$$`__`___```_X``_$$$$__``XXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"______XXXXXXXXXX_$$$$__`__XXX___``_XXX_XXXXXXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"______XXXXXX__```````___XXXXXXX__``````````_XXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"______XXXX_`````````XXXXXXXXXXXXXXX`````````__XXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"______X___```````````XXXXXXXXXXXXX_``````````____X" <<'\n'; 
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_XXXXXXXXXXXXXX_````_`X______XXXX_```````_XXXXXXXXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_______X__XXXX__``````_X_______X_```````________" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"__XX____X_____XX_``````________X````````___```_X__XXX_____XXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_______XXXX_````````````X_____X`````````````_XXX________XXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"___XX______X_````````````X___X_`````````````X______X__XXXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_____________X_``````````_X_X_````````````XX________XXXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_____________XXXX_````````_X__```````__XX___________XXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_____________XX__`_XXX___``_``___XXXX_XXX__________XXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"____________XXX__````````````````````_XXXX________XXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"____________XXX_``````````````````````XXXX_______XXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"____________XXX``````````````````````__XXX______XXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"___________XX__```````````````````````__XX_____XXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"__________XXXX_`````````````````````````_XX__XXXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"__________XXXX_`````````````````````````_XXXXXXXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_________XXXXX``````````````````````````_XXXXXXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_________XX__X`````````````````````````_XXXXXXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_________XXX___`````````X````X``````````X_XXXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_________XXXX_X_```````_X````_``````````X_XXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_________XXXX_X`````````X`````_`````````XXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_________XXXX___````````X`````X````````__XXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_________XXXXX_X````````X`````X````````__XXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"__________XXX__X_```````X`````X````````X_XXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"___________XXXXX_```````X`````X````````X_XXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"___________X_```X```````X`````X````````X___X" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"__________X____`X```````__````X```````__```_X" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"__________XX__X_X```````_XXXX_X```````_`___XX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"________XXXXXXXX``_`````_XXXXXX_```````XXXXXXX" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_______________X__`X``_XXXXXXXX_``````___X" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"________________XX_X__XXXXXXXXXXX```X__X" <<'\n';
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout <<"_________________XXXXXXXXXXXXXXXXXXXXXX" <<'\n';

    return 0;
}
